wwd_core.nominatim_settings:
  type: config_object
  label: 'Nominatim geocoding settings'
  mapping:
    nominatim_base_url:
      type: string
      label: 'Nominatim Base URL Override'
    nominatim_email:
      type: email
      label: 'Custom Email for Nominatim Requests'
