wwd_core.settings:
  type: config_object
  label: 'WWD Core settings'
  mapping:
    nominatim_base_url:
      type: string
      label: 'Nominatim Base URL Override'
    nominatim_email:
      type: email
      label: 'Custom Email for Nominatim Requests'
    mapbox_style:
      type: text
      label: 'Mapbox Style url'
    mapbox_token:
      type: text
      label: 'Mapbox Token'
